# https://golangci-lint.run/docs/configuration/file/
# https://github.com/golangci/golangci-lint/blob/HEAD/.golangci.reference.yml

version: "2"

linters:
  default: all
  disable:
    - cyclop
    - depguard
    - err113
    - exhaustruct
    - forbidigo
    - funlen
    - goprintffuncname
    - varnamelen
    - wrapcheck
    - wsl
  settings:
    gocritic:
      enable-all: true
    revive:
      enable-default-rules: true

formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
    - golines
